### ISSUE TITLE
"Complete" button in the middle of the survey & Question number reset to 1

### ISSUE THREAD

**Issue by tiffanylwt** [a2975667/cs598hs#2]
When a .js file ends, there is a "complete" button even though it is not the end of the survey yet. When a new .js file is loaded, the question numbering always restarts from 1.

**Comment by tiffanylwt** [comment]
![image](https://user-images.githubusercontent.com/14918381/55602346-b1846e80-572a-11e9-802d-e6db5da5573d.png)
We can probably use this.

**Comment by a2975667** [comment]
Number postponed. Complete fixed.
